### ISSUE TITLE
unknown parameter

### ISSUE THREAD

**Issue by krzysztof-sz** [obol89/zabbix-windows-disk-performance#1]
I have error:
C:\Program Files\Zabbix Agent>zabbix_agentd.exe --config zabbix_agentd.conf --start
zabbix_agentd.exe [24396]: Warning: EnableRemoteCommands parameter is deprecated, use AllowKey=system.run[*] or DenyKey=system.run[*] instead
zabbix_agentd.exe [24396]: unknown parameter "$drives" in config file "C:\Program Files\Zabbix Agent\zabbix_agentd.conf.d\discoverdisks.ps1", line 1

**Comment by obol89** [comment]
What version of Zabbix Server and Zabbix Agent do you use?

**Comment by krzysztof-sz** [comment]
My mistake. In zabbix agent config I add path to script through Include parameter. And you don't have to do that :)

**Comment by obol89** [comment]
Ok, cool. Thank you.
